DependenciesColumns:
  - component: Component
  - directory: Directory
  - upstream: Upstream
  - homepage: Homepage
Sections:
  - Compilation Infrastructure:
    bmake:
      - directory: contrib/bmake
      - upstream: NetBSD
      - homepage: https://www.NetBSD.org
    byacc:
      - directory: contrib/byacc
      - upstream: invisible-island
      - homepage: https://invisible-island.net/byacc/
    dtc:
      - directory: usr.bin/dtc
      - upstream: David Chisnall
      - homepage: https://github.com/davidchisnall/dtc
    elftoolchain:
      - directory: contrib/elftoolchain
      - upstream: elftoolchain
      - homepage: https://sourceforge.net/projects/elftoolchain/
    libcxxrt:
      - directory: contrib/libcxxrt
      - upstream:
      - homepage: https://github.com/libcxxrt/libcxxrt
    LLVM:
      - directory: contrib/llvm-project
      - upstream: LLVM
      - homepage: https://llvm.org
    unifdef:
      - directory: contrib/unifdef
      - upstream: Tony Finch
      - homepage: https://dotat.at/prog/unifdef
  - Kernel:
    acpi(4):
      - directory: sys/contrib/dev/acpica
      - upstream: Intel
      - homepage: https://github.com/acpica/acpica
    ice(4):
      - directory: sys/contrib/dev/ice
      - upstream: Intel
      - homepage: https://edc.intel.com/content/www/us/en/design/products/ethernet/adapters-and-devices-user-guide/dynamic-device-personalization-ddp/
    ipfilter(4):
      - directory: sys/netpfil/ipfilter
      - upstream: Phil Dibowitz
      - homepage: https://www.phildev.net/ipf/
    pf(4):
      - directory: sys/netpfil/pf
      - upstream: OpenBSD
      - homepage: https://openbsd.org
    umb(4):
      - directory: sys/dev/usb/net
      - upstream: OpenBSD
      - homepage: https://openbsd.org
    ZFS:
      - directory:
        - sys/contrib/openzfs
        - cddl
      - upstream: OpenZFS
      - homepage: https://openzfs.org/wiki/Main_Page
    zstd:
      - directory: sys/contrib/zstd
      - upstream: Meta
      - homepage: https://facebook.github.io/zstd/
  - Network Libraries:
    bsnmp:
      - directory: contrib/bsnmp
      - upstream: Hartmut Brandt
      - homepage: https://people.freebsd.org/~harti/bsnmp/
    ldns:
      - directory: contrib/ldns
      - upstream: NLnet Labs
      - homepage: https://github.com/NLnetLabs/ldns
    libpcap:
      - directory: contrib/libpcap
      - upstream: TCPdump
      - homepage: https://www.tcpdump.org
  - Network Services:
    blocklist:
      - directory: contrib/blocklist
      - upstream: NetBSD
      - homepage: https://www.NetBSD.org
    dma:
      - directory: contrib/dma
      - upstream: DragonFly BSD
      - homepage: https://www.dragonflybsd.org/handbook/mta/
    NTP:
      - directory: contrib/ntp
      - upstream: NTP Project
      - homepage: https://www.ntp.org
    OpenSSH:
      - directory: crypto/openssh
      - upstream: OpenBSD
      - homepage: https://openssh.com
    Sendmail:
      - directory: contrib/sendmail
      - upstream: Proofpoint
      - homepage: https://ftp.sendmail.org
    Unbound:
      - directory: contrib/unbound
      - upstream: NLnet Labs
      - homepage: https://github.com/NLnetLabs/unbound
    WireGuard:
      - directory: contrib/wireguard-tools
      - upstream: WireGuard
      - homepage: https://git.zx2c4.com/wireguard-tools/
    wpa_supplicant:
      - directory: contrib/wpa
      - upstream: Jouni Malinen
      - homepage: https://w1.fi/wpa_supplicant/
  - Network Tools:
    lib9p:
      - directory: contrib/lib9p
      - upstream: Conclusive Engineering
      - homepage: https://github.com/conclusiveeng/lib9p
    tcpdump:
      - directory: contrib/tcpdump
      - upstream: TCPdump
      - homepage: https://www.tcpdump.org
  - Security Infrastructure:
    BearSSL:
      - directory: contrib/bearssl
      - upstream: BearSSL
      - homepage: https://bearssl.org
    OpenSSL:
      - directory: crypto/openssl
      - upstream: OpenSSL
      - homepage: https://openssl-library.org
  - System Libraries:
    arm-optimized-routines:
      - directory: contrib/arm-optimized-routines
      - upstream: Arm
      - homepage: https://github.com/ARM-software/optimized-routines
    bionic-x86_64-string:
      - directory: contrib/bionic-x86_64-string
      - upstream: Intel
      - homepage: https://android.googlesource.com/platform/bionic
    bsddialog:
      - directory: contrib/bsddialog
      - upstream: Alfonso Siciliano
      - homepage: https://gitlab.com/alfix/bsddialog
    bzip2:
      - directory: contrib/bzip2
      - upstream: Julian Seward
      - homepage: https://sourceware.org/bzip2/
    flex:
      - directory: contrib/flex
      - upstream: Will Estes
      - homepage: https://github.com/westes/flex
    gdtoa:
      - directory: contrib/gdtoa
      - upstream: David M. Gay
      - homepage: https://www.netlib.org/fp/
    Heimdal Kerberos:
      - directory:
        - crypto/heimdal
        - contrib/com_err
      - upstream: Heimdal Software
      - homepage: https://www.heimdal.software
    jemalloc:
      - directory: contrib/jemalloc
      - upstream: jemalloc
      - homepage: https://jemalloc.net
    libarchive:
      - directory: contrib/libarchive
      - upstream: libarchive
      - homepage: https://libarchive.org
    libbegemot:
      - directory: contrib/libbegemot
      - upstream: Hartmut Brandt
      - homepage: https://people.freebsd.org/~harti/libbegemot/
    libcbor:
      - directory: contrib/libcbor
      - upstream: Pavel Kalvoda
      - homepage: https://github.com/PJK/libcbor
    libdialog:
      - directory: contrib/libdialog
      - upstream: invisible-island
      - homepage: https://invisible-island.net/dialog/
    libdiff:
      - directory: contrib/libdiff
      - upstream: Game of Trees
      - homepage: https://www.gameoftrees.org
    libedit:
      - directory: contrib/libedit
      - upstream: NetBSD
      - homepage: https://www.NetBSD.org
    libevent:
      - directory: contrib/libevent
      - upstream: libevent
      - homepage: https://libevent.org
    libexecinfo:
      - directory: contrib/libexecinfo
      - upstream: Maxim Sobolev
      - homepage: 
    libexpat:
      - directory: contrib/expat
      - upstream: expat
      - homepage: https://github.com/libexpat/libexpat
    libfido2:
      - directory: contrib/libfido2
      - upstream: Yubico
      - homepage: https://github.com/Yubico/libfido2
    liblzma:
      - directory: contrib/xz
      - upstream: Tukaani
      - homepage: https://tukaani.org/xz/
    libmagic (file):
      - directory: contrib/file
      - upstream: Ian Darwin
      - homepage: https://www.darwinsys.com/file/
    libucl:
      - directory: contrib/libucl
      - upstream: libucl
      - homepage: 
    libxo:
      - directory: contrib/libxo
      - upstream: Juniper
      - homepage: https://github.com/Juniper/libxo
    mandoc:
      - directory: contrib/mandoc
      - upstream: Ingo Schwarze
      - homepage: https://mandoc.bsd.lv
    ncurses:
      - directory: contrib/ncurses
      - upstream: invisible-island
      - homepage: https://invisible-island.net/ncurses/
    OpenPAM:
      - directory: contrib/openpam
      - upstream: OpenPAM
      - homepage: https://openpam.org
    SQLite:
      - directory: contrib/sqlite3
      - upstream: SQLite
      - homepage: https://sqlite.org/src
    Time Zone Database:
      - directory:
        - contrib/tzcode
        - contrib/tzdata
      - upstream: IANA
      - homepage: https://www.iana.org/time-zones
    zlib:
      - directory: contrib/zlib
      - upstream: zlib
      - homepage: https://zlib.net
  - System Tools:
    awk:
      - directory: contrib/one-true-awk
      - upstream: One True Awk
      - homepage: https://github.com/onetrueawk/awk
    bc:
      - directory: contrib/bc
      - upstream: Gavin D. Howard
      - homepage: https://gavinhoward.com/tag/bc/
    diff:
      - directory: contrib/diff
      - upstream: GNU
      - homepage: https://www.gnu.org/software/diffutils/
    ee:
      - directory: contrib/ee
      - upstream: Hugh Mahon
      - homepage: 
    hyperv:
      - directory: contrib/hyperv
      - upstream: Microsoft
      - homepage: 
    less:
      - directory: contrib/less
      - upstream: Mark Nudelman
      - homepage: https://www.greenwoodsoftware.com/less/
    Lua:
      - directory: contrib/lua
      - upstream: Lua
      - homepage: https://www.lua.org
  - Test Infrastructure:
    ATF:
      - directory: contrib/atf
      - upstream: Julio Merino
      - homepage: https://github.com/jmmv/atf
    capsicum-test:
      - directory: contrib/capsicum-test
      - upstream: University of Cambridge
      - homepage: https://www.cl.cam.ac.uk/research/security/capsicum/
    GoogleTest:
      - directory: contrib/googletest
      - upstream: Google
      - homepage: https://google.github.io/googletest/
    NetBSD tests:
      - directory: contrib/netbsd-tests
      - upstream: NetBSD
      - homepage: https://www.NetBSD.org
    pjdfstest:
      - directory: contrib/pjdfstest
      - upstream: pjdfstest
      - homepage: https://github.com/pjd/pjdfstest
