name: Re-generate the deliverables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  re-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Re-generate
        run: make
